[theme]
base = "dark"
primaryColor = "#2680EB"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#262626"
textColor = "#e0e0e0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
