[theme]
base = "dark"
primaryColor = "#2680EB"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#2d2d2d"
textColor = "#e0e0e0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
